---
- hosts:
    - consul_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - brianshumate.consul

- hosts:
    - vault_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - brianshumate.vault

- hosts:
    - nomad_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - geerlingguy.docker
    - brianshumate.nomad

- hosts: traefik_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  post_tasks:
    - name: Copy Traefik Config File
      template:
        src: templates/traefik.toml.j2
        dest: /etc/traefik.toml
  roles:
    - kibatic.traefik
  tasks:
    - name: Restart traefik
      service:
        name: traefik
        state: restarted
        enabled: yes
