---
- hosts:
    - consul_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
  - name: start consul
    ansible.builtin.service:
      name: consul
      state: started

- hosts:
    - vault_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
  - name: start vault
    ansible.builtin.service:
      name: vault
      state: started

- hosts:
    - docker_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
  - name: start nomad
    ansible.builtin.service:
      name: nomad
      state: started

- hosts: traefik_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
  - name: Stop traefik
    ansible.builtin.service:
      name: traefik
      state: started
