---
version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/ansible"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/terraform/infrastructure"
  NOMAD_DIR: "{{.PROJECT_DIR}}/nomad"
  STATE_DIR: "{{.TERRAFORM_DIR}}/terraform.tfstate.d/{{.ENVIRONMENT}}"

dotenv: [".env"]

includes:
  ansible: .taskfiles/ansible.yml
  checkov: .taskfiles/checkov.yml
  consul: .taskfiles/consul.yml
  nomad: .taskfiles/nomad.yml
  terraform: .taskfiles/terraform.yml
  vault: .taskfiles/vault.yml
