nomad_bind_address: "0.0.0.0"
nomad_datacenter: "{{ lookup('env', 'ENVIRONMENT') }}"
nomad_domain: "{{ lookup('env', 'DOMAIN') }}"
nomad_servers: ["nomad-servers.service.{{ lookup('env', 'DOMAIN') }}:4647"]
nomad_encrypt: true
nomad_acl_enabled: true
nomad_acl_replication_token: "{{ lookup('env', 'NOMAD_ACL_REPLICATION_TOKEN') }}"
nomad_use_consul: yes
nomad_consul_address: http://127.0.0.1:8500
nomad_consul_token: "{{ lookup('env', 'CONSUL_ACL_TOKEN') }}"
nomad_vault_enabled: yes
nomad_vault_address: "http://active.vault.service.{{ lookup('env', 'DOMAIN') }}:8200"
nomad_vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
nomad_options: {  'driver.raw_exec.enable': '1' }
nomad_network_speed: 10
nomad_bootstrap_expect: 1
nomad_docker_enable: yes
permanent: yes
nomad_ports_http: 4646
nomad_ports_rpc: 4647
nomad_ports_serf: 4648