---
nomad_datacenter: "{{ lookup('env', 'ENVIRONMENT') }}"
nomad_encrypt_enable: true
nomad_use_consul: true
nomad_vault_enabled: yes
nomad_vault_address: "http://active.vault.service.{{ lookup('env', 'DOMAIN') }}:8200"
nomad_vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
nomad_options: { 'driver.raw_exec.enable': '1' }
nomad_network_speed: 10
nomad_docker_enable: yes
